# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_product.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddProductDialog(object):
    def setupUi(self, AddProductDialog):
        AddProductDialog.setObjectName("AddProductDialog")
        AddProductDialog.resize(400, 213)
        AddProductDialog.setStyleSheet("background-color: #f5f5f5;")
        self.verticalLayout = QtWidgets.QVBoxLayout(AddProductDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(AddProductDialog)
        self.label.setStyleSheet("font-size: 16px; font-weight: bold;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.nameLabel = QtWidgets.QLabel(AddProductDialog)
        self.nameLabel.setObjectName("nameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nameLabel)
        self.nameInput = QtWidgets.QLineEdit(AddProductDialog)
        self.nameInput.setObjectName("nameInput")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nameInput)
        self.priceLabel = QtWidgets.QLabel(AddProductDialog)
        self.priceLabel.setObjectName("priceLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.priceLabel)
        self.priceInput = QtWidgets.QDoubleSpinBox(AddProductDialog)
        self.priceInput.setMaximum(1000000.0)
        self.priceInput.setObjectName("priceInput")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.priceInput)
        self.weightLabel = QtWidgets.QLabel(AddProductDialog)
        self.weightLabel.setObjectName("weightLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.weightLabel)
        self.weightInput = QtWidgets.QDoubleSpinBox(AddProductDialog)
        self.weightInput.setMaximum(1000.0)
        self.weightInput.setSingleStep(0.1)
        self.weightInput.setObjectName("weightInput")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.weightInput)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.addButton = QtWidgets.QPushButton(AddProductDialog)
        self.addButton.setStyleSheet("background-color: #4CAF50; color: white; padding: 8px;")
        self.addButton.setObjectName("addButton")
        self.buttonLayout.addWidget(self.addButton)
        self.cancelButton = QtWidgets.QPushButton(AddProductDialog)
        self.cancelButton.setStyleSheet("background-color: #f44336; color: white; padding: 8px;")
        self.cancelButton.setObjectName("cancelButton")
        self.buttonLayout.addWidget(self.cancelButton)
        self.verticalLayout.addLayout(self.buttonLayout)

        self.retranslateUi(AddProductDialog)
        self.cancelButton.clicked.connect(AddProductDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(AddProductDialog)

    def retranslateUi(self, AddProductDialog):
        _translate = QtCore.QCoreApplication.translate
        AddProductDialog.setWindowTitle(_translate("AddProductDialog", "Добавление товара"))
        self.label.setText(_translate("AddProductDialog", "Добавление нового товара"))
        self.nameLabel.setText(_translate("AddProductDialog", "Название товара:"))
        self.priceLabel.setText(_translate("AddProductDialog", "Цена (₽):"))
        self.weightLabel.setText(_translate("AddProductDialog", "Вес (кг):"))
        self.addButton.setText(_translate("AddProductDialog", "Добавить"))
        self.cancelButton.setText(_translate("AddProductDialog", "Отмена"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddProductDialog = QtWidgets.QDialog()
    ui = Ui_AddProductDialog()
    ui.setupUi(AddProductDialog)
    AddProductDialog.show()
    sys.exit(app.exec_())
